
services:
  wg-api:
    build:
      context: ./services/wg-api
      dockerfile: Dockerfile
    ports:
      - "51820:51820"
      - "8080:8080"
    volumes:
      - ./services/wg-api:/app
    environment:
      - TZ=Europe/Moscow
    cap_add:
      - NET_ADMIN
      - SYS_MODULE


