
services:
  wg-api:
    build:
      context: ./services/wg-api
      dockerfile: Dockerfile
    ports:
      - "51820:51820"
      - "8000:8000"
    volumes:
      - ./services/wg-api:/app
    environment:
      - TZ=Europe/Moscow
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  tg-bot:
    build:
      context: ./services/telegram-bot
      dockerfile: Dockerfile
    volumes:
      - ./services/tg-bot:/app
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - wg-api
    env_file:
      - .env